export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const GETUSER = 'GETUSER';
export const GETALLUSERS = 'GETALLUSERS';
export const EMPTY_USER = 'EMPTY_USER';

export const GETSERVICES = 'GETSERVICES';
export const GETPAGINATEDSERVICES = 'GETPAGINATEDSERVICES';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';

export const GET_CLASIFICADO = 'GET_CLASIFICADO';
export const GETOFFERBYEMAIL = 'GETOFFERBYEMAIL';
export const DELETECLASIFICADOS = 'DELETECLASIFICADOS';

export const ADDCARTSERVICES = 'ADDCARTSERVICES';
export const DELETECARTSERVICES = 'DELETECARTSERVICES';
export const EMPTYCARTSERVICES = 'EMPTYCARTSERVICES'

export const GETALLRATING = 'GETALLRATING';
export const GETRATINGBYSERVICE = 'GETRATINGBYSERVICE';
export const GETALLRATINGBYUSER = 'GETALLRATINGBYUSER';
export const GETRATINGBYID = 'GETRATINGBYID'

export const GETNOTICES = "GETNOTICES"
