export const GETUSER = 'GETUSER'
export const GETSERVICES= 'GETSERVICES'
export const GETPAGINATEDSERVICES = 'GETPAGINATEDSERVICES'
export const SET_TOTAL_PAGES= 'SET_TOTAL_PAGES'
export const EMPTY_USER = 'EMPTY_USER';
export const ORDER_BY_NAME = "ORDER_BY_NAME"
export const FILTER_BY_TYPE = "FILTER_BY_TYPE"

