export const GETUSER = 'GETUSER'
export const GETSERVICES= 'GETSERVICES'
export const GETPAGINATEDSERVICES = 'GETPAGINATEDSERVICES'
export const SET_TOTAL_PAGES= 'SET_TOTAL_PAGES'
export const EMPTY_USER = 'EMPTY_USER';
export const ADDCARTSERVICES = 'ADDCARTSERVICES'
export const DELETECARTSERVICES = 'DELETECARTSERVICES'